-- // Creating project tables
-- Migration SQL that makes the change goes here.

CREATE TABLE IF NOT EXISTS `customers` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `NAME` varchar(250) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
 `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `responsibles` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `EXTERNAL_ID` int(11) NOT NULL DEFAULT '0',
 `NAME` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
 `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `technics` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `EXTERNAL_ID` int(11) NOT NULL,
 `NAME` varchar(250) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
 `STATE_NUMBER` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
 `LOADING_CAPACITY` int(11) NOT NULL,
 `PARTNER_ID` int(11) NOT NULL,
 `PARTNER_NAME` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
 `IS_MY` int(11) NOT NULL DEFAULT '0',
 `IS_VISIBILITY` int(11) NOT NULL DEFAULT '1',
 `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `contents` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `SPECIFICATION_ID` int(11) NOT NULL,
 `TECHNIC_ID` int(11) NOT NULL,
 `BEGIN_DATE` date NOT NULL,
 `FINISH_DATE` date NOT NULL,
 `DEAL_URL` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `RESPONSIBLE_ID` int(11) NOT NULL,
 `CUSTOMER_ID` int(11) NOT NULL,
 `WORK_ADDRESS` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `STATUS` int(11) NOT NULL,
 `IS_CLOSED` int(11) NOT NULL DEFAULT '0',
 `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `comments` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `CONTENT_ID` int(11) NOT NULL,
 `USER_ID` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
 `VALUE` text COLLATE utf8_unicode_ci NOT NULL,
 `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- @UNDO
-- SQL to undo the change goes here.

DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `contents`;
DROP TABLE IF EXISTS `technics`;
DROP TABLE IF EXISTS `responsibles`;
DROP TABLE IF EXISTS `customers`;

